protected/controllers/WorkerController.php
<?php

class WorkerController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column1';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

    public function actionReport($id=null)
    {
        if($id==null)
            $id = Yii::app()->user->id;

        if(isset($_POST['set_month'])){
            Yii::app()->session['month'] = $_POST['month'];
            Yii::app()->session['year'] = $_POST['year'];
        }

        // set month base on session
        if(Yii::app()->session['month']){
            $month =Yii::app()->session['month']; // get month from session
        }
        else{
            $month  = date('m'); // get current month
        }

        // set year base on session
        if(Yii::app()->session['year']){
            $year =Yii::app()->session['year']; // get year from session
        }
        else{
            $year  = date('Y'); // get current year
        }
        $worker = TblUsers::model()->findByPk($id);

        // find working hours
        $getWorkingDay = Schedules::model()->with(array(
            'shift'=>array(
                'condition'=>'off=0',
            )
        ))->findAll(array(
            'condition'=>'MONTH(date) = :month and YEAR(date) = :year and user_id=:id',
            'params'=>array(
                ':month'=>$month,
                ':year'=>$year,
                ':id'=>$id
            ),
            'order'=>'date ASC',
        ));
        $totalWorkingDays = count($getWorkingDay);
        $working_hours = count($getWorkingDay) * 7;

        // find off day
        $offDay = Schedules::model()->with(array(
            'shift'=>array(
                'condition'=>'off=1',
            )
        ))->findAll(array(
            'condition'=>'MONTH(date) = :month and YEAR(date) = :year and user_id=:id',
            'params'=>array(
                ':month'=>$month,
                ':year'=>$year,
                ':id'=>$id
            ),
            'order'=>'date ASC',
        ));
        $totalOffDay = count($offDay);

        // try to get data by same month and year. If found, delete current data and insert new record
        $find_schedule = Schedules::model()->findAll(array(
            'condition'=>'MONTH(date) = :month and YEAR(date) = :year and user_id=:id',
            'params'=>array(
                ':month'=>$month,
                ':year'=>$year,
                ':id'=>$id
            ),
            'order'=>'date ASC',
        ));

        $this->render('report', compact('worker', 'month','year', 'find_schedule','working_hours', 'totalOffDay', 'totalWorkingDays'));
    }

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
        // create new object
		$model=new TblUsers;
        $profile=new TblProfiles;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['TblUsers']))
		{
            // get post data
			$model->attributes      =$_POST['TblUsers'];
			$profile->attributes    =$_POST['TblProfiles'];

            // set validation
            $valid = $model->validate();
            $valid = $profile->validate() & $valid;

            if($valid){
                try
                {
                    $transaction = $model->getDbConnection()->beginTransaction();


                    // set as no ic is default password
                    $model->password = Yii::app()->getModule('user')->encrypting($profile->nokp);
                    $model->activkey=Yii::app()->getModule('user')->encrypting(microtime().$profile->nokp);

                    $model->status = 1;

                    // save user model
                    $model->save();

                    // save user profile
                    $profile->user_id = $model->id;
                    $profile->save();

                    // add on table authassignment
                    $authorizer = Yii::app()->getModule("rights")->getAuthorizer();
                    $authorizer->authManager->assign('worker', $model->id);

                    $transaction->commit();

                    Yii::app()->user->setFlash('success', 'Data Insert!');
                    $this->redirect(array('/worker'));

                }
                catch(Exception $e)
                {
                    $transaction->rollback();
                    Yii::app()->user->setFlash('error', 'Error while inserting data!');
                    $this->redirect(array('/worker'));
                }

            }
		}

        // call view
		$this->render('create',array(
			'model'=>$model,
            'profile'=>$profile,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['TblUsers']))
		{
			$model->attributes=$_POST['TblUsers'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}

	/**
	 * Manages all models.
	 */
	public function actionIndex()
	{
		$model=new TblUsers('worker');
		$model->unsetAttributes();  // clear any default values

		if(isset($_GET['TblUsers']))
			$model->attributes=$_GET['TblUsers'];

		$this->render('index',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return TblUsers the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=TblUsers::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param TblUsers $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='tbl-users-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/layouts/_sidebar.php
<ul class="sidebar-menu">
	<li class="header">MENU UTAMA</li>
	<!-- Optionally, you can add icons to the links -->

    <!-- menu for admin sahaja -->
    <?php if (Yii::app()->getModule('user')->isAdmin()){ ?>

        <!-- menu user -->
        <li class="treeview <?php echo (in_array(Yii::app()->controller->id, array('admin')))?"active":"" ?>">
            <a href="#"><i class="fa fa-user"></i> <span>Users</span> <i class="fa fa-angle-left pull-right"></i></a>
            <ul class="treeview-menu">
                <li><a href="<?php echo Yii::app()->createUrl('/user/admin/create') ?>"><i class="fa fa-plus"></i> Create</a></li>
                <li><a href="<?php echo Yii::app()->createUrl('/user/admin') ?>"><i class="fa fa-th"></i> List</a></li>
            </ul>
        </li>

        <!-- menu role management -->
        <li class=" <?php echo (in_array(Yii::app()->controller->id, array('brands')))?"active":"" ?>">
            <a href="<?php echo Yii::app()->createUrl('/rights') ?>"><i class="fa fa-desktop"></i> <span>Role Management</span></a>
        </li>

    <?php } else { ?>

        <!-- selain dari admin -->

        <!-- supervisor -->
        <?php if(Yii::app()->user->checkAccess('supervisor')) { ?>

            <!-- worker -->
            <li class=" <?php echo (in_array(Yii::app()->controller->id, array('worker')))?"active":"" ?>">
                <a href="<?php echo Yii::app()->createUrl('/worker') ?>"><i class="fa fa-users"></i> <span>Workers</span></a>
            </li>

            <!-- shift -->
            <li class=" <?php echo (in_array(Yii::app()->controller->id, array('shifts')))?"active":"" ?>">
                <a href="<?php echo Yii::app()->createUrl('/shifts') ?>"><i class="fa fa-desktop"></i> <span>Manage Shift</span></a>
            </li>

            <!-- menu venue -->
            <li class=" <?php echo (in_array(Yii::app()->controller->id, array('venue')))?"active":"" ?>">
                <a href="<?php echo Yii::app()->createUrl('/venue') ?>"><i class="fa fa-desktop"></i> <span>Manage Venue</span></a>
            </li>


            <!-- menu generate schedule -->
            <li class=" <?php echo (in_array(Yii::app()->controller->id, array('generateSchedule')))?"active":"" ?>">
                <a href="<?php echo Yii::app()->createUrl('/generateSchedule') ?>"><i class="fa fa-calendar"></i> <span>Schedule</span></a>
            </li>


        <?php } ?>

        <?php if(Yii::app()->user->checkAccess('worker')) { ?>
        <!-- worker -->
            <li class=" <?php echo (in_array(Yii::app()->controller->id, array('worker')))?"active":"" ?>">
                <a href="<?php echo Yii::app()->createUrl('/worker/report') ?>"><i class="fa fa-calendar"></i> <span>View Report</span></a>
            </li>

        <?php } ?>


        <!-- guest -->
        <?php if(Yii::app()->user->isGuest) { ?>

            <li>
                <a href="<?php echo Yii::app()->createUrl('user/login');?>">
                    <i class="fa fa-lock"></i>
                    <span>
                        Login
                    </span>
                </a>
            </li>            

        <?php } ?>
    <?php } ?>

</ul><!-- /.sidebar-menu -->

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="row">
	<div class="col-md-3">
        <div class="well well-small">
            <?php
//            $this->widget(
//                'booster.widgets.TbMenu',
//                array(
//                    'type' => 'pill',
//                    'items' => array(
//                        array(
//                            'label' => 'List header',
//                            'itemOptions' => array('class' => 'nav-header')
//                        ),
//                        array(
//                            'label' => 'Home',
//                            'url' => '#',
//                            'itemOptions' => array('class' => 'active')
//                        ),
//                        array('label' => 'Library', 'url' => '#'),
//                        array('label' => 'Applications', 'url' => '#'),
//                        array(
//                            'label' => 'Another list header',
//                            'itemOptions' => array('class' => 'nav-header')
//                        ),
//                        array('label' => 'Profile', 'url' => '#'),
//                        array('label' => 'Settings', 'url' => '#'),
//                        '',
//                        array('label' => 'Help', 'url' => '#'),
//                    )
//                )
//            );
            ?>
		<?php
			$this->widget('booster.widgets.TbMenu', array(
                'type' => 'lists',
				'items'=>$this->menu,
//				'htmlOptions'=>array('class'=>'operations'),
			));
		?>
        </div>
	</div>
	<div class="col-sm-9">
		<?php echo $content; ?>
	</div>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/login.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/AdminLTE/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/AdminLTE/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/AdminLTE/plugins/iCheck/square/blue.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="login-page">
    <div class="login-box" style="width: 450px;">
      <div class="login-logo">
        <a href="<?php echo Yii::app()->createUrl('/');?>"><b><?php echo Yii::app()->name; ?></b></a>
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
        <?php echo $content ?>
        <a href="<?php echo Yii::app()->createUrl('user/recovery') ?>">Forgot Password</a><br>
        <a href="<?php echo Yii::app()->createUrl('user/registration') ?>" class="text-center">Register Account</a>

      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->

    <!-- jQuery 2.1.3 -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/AdminLTE/plugins/jQuery/jQuery-2.1.3.min.js"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/AdminLTE/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/AdminLTE/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
  </body>
</html>

protected/views/layouts/main_bak.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="language" content="en">

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print">
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection">
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css">

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Home', 'url'=>array('/site/index')),
				array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
				array('label'=>'Contact', 'url'=>array('/site/contact')),
				array('label'=>'Kids', 'url'=>array('/kids/admin'), 'visible'=>Yii::app()->user->checkAccess('parent')),
				array('label'=>'Murid', 'url'=>array('/kids/admin'), 'visible'=>(Yii::app()->user->checkAccess('branch_manager')||Yii::app()->user->checkAccess('branch_owner')||Yii::app()->user->checkAccess('teacher'))),
				array('label'=>'Branch', 'url'=>array('/branchs'), 'visible'=>(Yii::app()->getModule('user')->isAdmin() || Yii::app()->user->checkAccess('branch_owner'))),
				array('label'=>'Users', 'url'=>array('/user/admin'), 'visible'=>Yii::app()->getModule('user')->isAdmin()),
				array('url'=>Yii::app()->getModule('user')->loginUrl, 'label'=>Yii::app()->getModule('user')->t("Login"), 'visible'=>Yii::app()->user->isGuest),
				array('url'=>Yii::app()->getModule('user')->registrationUrl, 'label'=>Yii::app()->getModule('user')->t("Register"), 'visible'=>Yii::app()->user->isGuest),
				array('url'=>Yii::app()->getModule('user')->profileUrl, 'label'=>Yii::app()->getModule('user')->t("Profile"), 'visible'=>!Yii::app()->user->isGuest),
				array('url'=>Yii::app()->getModule('user')->logoutUrl, 'label'=>Yii::app()->getModule('user')->t("Logout").' ('.Yii::app()->user->name.')', 'visible'=>!Yii::app()->user->isGuest),
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>

protected/views/layouts/registration.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/AdminLTE/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/AdminLTE/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/AdminLTE/plugins/iCheck/square/blue.css" rel="stylesheet" type="text/css" />
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="register-page">
    <div class="register-box" style="margin-top:-5px; width:550px;">
      <div class="register-logo">
        <a href="<?php echo Yii::app()->createUrl('/');?>"><b>Tadika</b> ABS</a>

      </div>

      <div class="register-box-body">
        <p class="login-box-msg">Pendaftaran Ibu Bapa</p>
        <?php echo $content; ?>
        <a href="<?php echo Yii::app()->createUrl('/user/login') ?>" class="text-center">Saya telah mempunyai akaun</a>
      </div><!-- /.form-box -->
    </div><!-- /.register-box -->

    <!-- jQuery 2.1.3 -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/AdminLTE/plugins/jQuery/jQuery-2.1.3.min.js"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/AdminLTE/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/AdminLTE/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
  </body>
</html>